name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -o ./.deploy/TableServiceApi -r linux-x64
    - name: Build Deployment Package
      run: zip -r ./.deploy/TableServiceApi-package.zip ./.deploy/TableServiceApi
    - uses: actions/upload-artifact@master
      with:
        name: Zip Package
        path: ./.deploy/TableServiceApi-package.zip
  
  deploy_dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@master
        with:
          name: Zip Package
          path: ./.deploy/TableServiceApi-package.zip

      - name: Deploy to AWS Beanstalk
        uses: einaregilsson/beanstalk-deploy@v10
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
          application_name: BuildWithRebaseCore
          environment_name: Buildwithrebasecore-env
          version_label: "build-with-rebase-core-${{ steps.format-time.outputs.replaced }}"
          deployment_package: ./.deploy/TableServiceApi-package.zip

